
from pyspark import SparkConf,SparkContext
from pyspark.streaming import StreamingContext
import sys
from operator import add
import json

import re 

# Emoji regex generated by ChatGPT
emoji_pattern = re.compile(
    "[" 
    u"\U0001F600-\U0001F64F"  # emoticons
    u"\U0001F300-\U0001F5FF"  # symbols & pictographs
    u"\U0001F680-\U0001F6FF"  # transport & map
    u"\U0001F1E0-\U0001F1FF"  # flags
    u"\U0001F900-\U0001F9FF"  # supplemental symbols
    u"\U00002600-\U000026FF"  # misc symbols
    "]+", flags=re.UNICODE
)

def contains_emoji(text):
    return bool(emoji_pattern.search(text))

def classify_record(tweet):
    tweet = tweet.lower()

    health_words = [
        "doctor", "patient", "disease", "health", "cancer", "medical", "emergency",
        "medicine", "hospital", "clinical", "nutrition", "deficiency", "allergy",
        "immunity", "immunization", "virus", "antibiotic", "chromosome", "flu"
    ]
    
    not_health_words = [
        "pain in the ass", "fever dream", "OMG", "cabin fever", 
        "heartache", "love sick", "sick of this", "sick and tired", "fire",
        "banger", "song", "club", "party", "vibe", "sheesh", "morbius fever", 
        "sick leave", "gamers"
    ]

    for phrase in not_health_words:
        if phrase in tweet:
            return False
        
    if contains_emoji(tweet):
        return False
    
    return any(word in tweet for word in health_words)

conf = SparkConf()
conf.setAppName("Task3")

sc = SparkContext(conf=conf)
sc.setLogLevel("FATAL")

ssc = StreamingContext(sc, 1)
ssc.checkpoint("checkpoint_TwitterApp")

dataStream = ssc.socketTextStream("localhost", 9025)

keywords = ["fever", "ache", "pain", "sick"]
filtered = dataStream.filter(lambda tweet: any(word in tweet.lower() for word in keywords))

windowedDataStream = filtered.window(300, 5)

classified = windowedDataStream.map(lambda tweet: (1 if classify_record(tweet) else 0, 1))

counts = classified.reduce(lambda a, b: (a[0] + b[0], a[1] + b[1]))

def compute_percentage(rdd):
    if not rdd.isEmpty():
        for (health_count, total) in rdd.collect():
            if total != 0:
                percentage = (health_count / total) * 100
                print(f"(Health tweet percentage: {percentage:.2f}%)")
            else:
                print("(Health tweet percentage: 0.00%)")

counts.foreachRDD(compute_percentage)

# Start streaming
ssc.start()
ssc.awaitTermination()
